name: Django CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on any push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # The job runs on the latest Ubuntu image

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Use Python 3.11 for the environment

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install all dependencies from requirements.txt
        pip install coverage            # Install coverage for code coverage tracking

    # Step 4: Run Unit and Integration tests
    - name: Run Unit and Integration tests along with E2E tests perfectly
      run: |
        python manage.py test  # Run unit and integration tests
        coverage run manage.py test  # If you are using coverage, this will collect data
        coverage report  # Display the coverage report

  
    # Step 6: Run linting tools (Flake8 and Black)
    - name: Run linting tools
      run: |
        pip install flake8 black  # Install linting tools
        black --check .  # Run Black in check mode (checks if the code follows PEP 8)

  deploy:
    needs: test  # Deploy only after tests pass
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v2

    # Step 2: Set up Python and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Step 3: Deploy to PythonAnywhere using the API key
    - name: Clone and fix pythonanywhere-cli
      run: |
        git clone https://github.com/cfc603/pythonanywhere-cli.git
        cd pythonanywhere-cli
        # Remove the 'universal' option in setup.cfg
        sed -i '/universal = 1/d' setup.cfg
        # Build the wheel manually
        python setup.py bdist_wheel
        # Install the modified wheel
        pip install dist/pythonanywhere_cli-0.3.0-py3-none-any.whl

    - name: Deploy to PythonAnywhere
      env:
        PYTHONANYWHERE_API_KEY: ${{ secrets.Python_Anywhere }}
      run: |
        pythonanywhere --api-key ${{ secrets.Python_Anywhere }} deploy /todo
